# Generated by Django 5.0.7 on 2024-07-16 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDepartment',
            fields=[
                ('sys_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Sys ID')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Name')),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Contact')),
                ('business_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=255, null=True)),
                ('department_head', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Head')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('head_count', models.PositiveIntegerField(default=0)),
                ('ID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sys_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Sys ID')),
                ('user_id', models.PositiveIntegerField(default=0, verbose_name='User ID')),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_number', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('N/A', 'N A')], max_length=255, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Phone')),
                ('mobile_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Phone')),
                ('business_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Phone')),
                ('internal_integration_user', models.PositiveIntegerField(blank=True, default=0, verbose_name='Internal Integration User')),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('calendar', models.CharField(blank=True, max_length=255, null=True)),
                ('calendar_integration', models.CharField(blank=True, choices=[('OUTLOOK', 'Outlook'), ('GOOGLE_CALENDAR', 'Google Calender')], max_length=255, null=True, verbose_name='Calender Integration')),
                ('ldap_server', models.CharField(blank=True, max_length=255, null=True, verbose_name='LDAP Server')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('notification', models.CharField(blank=True, choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='DISABLED', max_length=255)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('sso_source', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_days', models.PositiveIntegerField(default=0)),
                ('vip_access_only', models.PositiveIntegerField(default=0, verbose_name='VIP\tWeb service access only')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center')),
                ('country_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Code')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State / Province')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip / Postal Code')),
                ('date_format', models.CharField(blank=True, choices=[('YYYY-MM-DD', 'Yyyy Mm Dd'), ('MM-DD-YYYY', 'Mm Dd Yyyy'), ('DD-MM-YYYY', 'Dd Mm Yyyy')], max_length=255, null=True, verbose_name='Date Format')),
                ('time_format', models.CharField(blank=True, choices=[('12 HOUR', 'Hour 12'), ('24 HOUR', 'Hour 24')], max_length=255, null=True, verbose_name='Time Format')),
                ('defualt_perspective', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.TimeField()),
                ('is_multifactor_enabled', models.BooleanField(blank=True, default=False, verbose_name='Enable Multifactor Authentication')),
                ('falied_login', models.PositiveIntegerField(blank=True, default=0, verbose_name='Failed Login Attempts')),
                ('password_needs_reset', models.BooleanField(blank=True, default=False, verbose_name='Password Needs Reset')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Sys User',
                'verbose_name_plural': 'Sys Users',
            },
        ),
    ]
