# Generated by Django 5.0.7 on 2024-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
