# Generated by Django 5.0.7 on 2024-07-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0002_sysuser_is_active_sysuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='time',
        ),
    ]
