# Generated by Django 5.0.7 on 2024-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0004_rename_falied_login_sysuser_failed_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='department',
            field=models.CharField(blank=True, choices=[('営業本部 / Sales Division', 'Sales Division'), ('ソリューション営業部 / Solution sales department', 'Solution Sales Department'), ('システム事業部 / System Division', 'System Division'), ('研究開発課 / Research and development section', 'Research And Development Section'), ('システム課 / System section', 'System Section'), ('SW開発課 / software development section', 'Software Development Section'), ('ITサポート事業部\t/ IT Support Division', 'It Support Division'), ('購買調達部\t/ Purchasing and Procurement Department', 'Purchasing And Procurement Department'), ('管理部\t/ Management Department', 'Management Department')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='title',
            field=models.CharField(blank=True, choices=[('代表取締役', '代表取締役'), ('本部長', '本部長'), ('事業部長', '事業部長'), ('部長', '部長'), ('課長', '課長'), ('担当課長', '担当課長'), ('主任', '主任'), ('主任２', '主任2'), ('課員', '課員')], max_length=255, null=True),
        ),
    ]
