# Generated by Django 5.0.7 on 2024-07-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0005_alter_sysuser_department_alter_sysuser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
