# Generated by Django 5.0.7 on 2024-07-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0006_sysuser_division_sysuser_group_sysuser_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='department',
            field=models.CharField(blank=True, choices=[('営業本部', '営業本部 Sales Division'), ('システム事業部', 'システム事業部 System Division'), ('ITサポート事業部', 'Itサポート事業部 It Support Division'), ('管理部', '管理部 Management Department'), ('N/A', 'N A')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='division',
            field=models.CharField(blank=True, choices=[('ソリューション営業部', 'ソリューション営業部 Solution Sales Department'), ('研究開発課', '研究開発課 Research And Development Section'), ('システム課', 'システム課 System Section'), ('SW開発課', 'Sw開発課 Software Development Section'), ('購買調達部', '購買調達部 Purchasing And Procurement Department')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='group',
            field=models.CharField(blank=True, choices=[('1G', 'G1'), ('2G', 'G2'), ('3G', 'G3'), ('4G', 'G4'), ('N/A', 'N A')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='section',
            field=models.CharField(blank=True, choices=[('1課', '課 1'), ('2課', '課 2'), ('N/A', 'N A')], max_length=255, null=True),
        ),
    ]
