# Generated by Django 5.0.7 on 2024-07-29 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0009_alter_commondepartment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondepartment',
            name='department_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commondepartment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgchart.commondepartment'),
        ),
        migrations.AlterField(
            model_name='commondepartment',
            name='primary_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
