# Generated by Django 5.0.7 on 2024-07-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0010_alter_commondepartment_department_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondepartment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgchart.commondepartment'),
        ),
    ]
